version: '3.8'

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    container_name: timescaledb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: data226
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: stockdw
    volumes:
      - ./data/db:/var/lib/postgresql/data

  airflow-webserver:
    image: apache/airflow:2.7.3
    container_name: airflow-webserver
    restart: always
    depends_on:
      - timescaledb
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://data226:12345678@timescaledb:5432/stockdw
      AIRFLOW__WEBSERVER__SECRET_KEY: my_super_secret_key
      AIRFLOW__CORE__FERNET_KEY: f8nSfkKjNwYaJmd_Tr6JvACFpVoOgmHiSlXfiUiQvmM=
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./sql:/opt/airflow/sql
      - ./requirements.txt:/requirements.txt
      

    ports:
      - "8081:8080"
    command: >
      bash -c "
      pip install -r /requirements.txt &&
      airflow db migrate &&
      airflow users create --username admin --password admin --firstname Air --lastname Flow --role Admin --email admin@example.com &&
      airflow webserver"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  airflow-scheduler:
    image: apache/airflow:2.7.3
    container_name: airflow-scheduler
    restart: always
    depends_on:
      - timescaledb
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://data226:12345678@timescaledb:5432/stockdw
      AIRFLOW__WEBSERVER__SECRET_KEY: my_super_secret_key
      AIRFLOW__CORE__FERNET_KEY: f8nSfkKjNwYaJmd_Tr6JvACFpVoOgmHiSlXfiUiQvmM=
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./sql:/opt/airflow/sql
      - ./requirements.txt:/requirements.txt
    command: >
      bash -c "
      pip install -r /requirements.txt &&
      airflow scheduler"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: stock-data-platform-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: stock-data-platform-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://stock-data-platform-kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1


  kafka-producer:
    build:
      context: .
      dockerfile: Dockerfile.producer
    container_name: stock-data-platform-kafka-producer
    depends_on:
      - kafka
    restart: always

  kafka-consumer:
    build:
      context: .
      dockerfile: Dockerfile.consumer
    container_name: stock-data-platform-kafka-consumer
    depends_on:
      - kafka
      - timescaledb
    restart: always



